services:
  backend:
    build: ./backend
    env_file:
      - ./envs/.env.dev # <-- switch this per environment
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./recipe_app_ui
    env_file:
      - ./envs/.env.dev
    volumes:
      - ./recipe_app_ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
