version: "3.9"

services:
  backend-test:
    build: ./backend
    command: pytest
    env_file:
      - ./backend/envs/.env.test
    volumes:
      - ./backend/test-logs:/app/test-logs

  frontend-test:
    build:
      context: ./recipe_app_ui
      dockerfile: Dockerfile
    command: npm run test:ci
    volumes:      
      - ./recipe_app_ui/test-logs:/app/test-logs
      - /app/node_modules
